Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,6 +1,5 @@
 name: CI/CD
 
-# Exclude the workflow to run on changes to the helm chart
 on:
   pull_request:
     branches:
@@ -18,84 +17,88 @@ on:
       - 'helm/**'
 
 jobs:
-
   build:
+    if: ${{ github.event_name != 'push' }}
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Set up Go 1.22
-      uses: actions/setup-go@v2
-      with:
-        go-version: 1.22
+      - name: Set up Go 1.22
+        uses: actions/setup-go@v2
+        with:
+          go-version: 1.22
 
-    - name: Build
-      run: go build -o go-web-app
+      - name: Build
+        run: go build -o go-web-app
 
-    - name: Test
-      run: go test ./...
-  
+      - name: Test
+        run: go test ./...
+
   code-quality:
+    if: ${{ github.event_name != 'push' }}
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Run golangci-lint || true
-      uses: golangci/golangci-lint-action@v6
-      with:
-        version: v1.56.2
-  
+      - name: Install golangci-lint
+        run: |
+          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.62.0/golangci-lint-1.62.0-linux-amd64.tar.gz | tar -xzv -C /tmp
+          sudo mv /tmp/golangci-lint-1.62.0-linux-amd64/golangci-lint /usr/local/bin
+
+      - name: Run golangci-lint
+        run: golangci-lint run
+
   push:
+    if: ${{ github.event_name != 'push' }}
     runs-on: ubuntu-latest
-
     needs: build
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v1
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
 
-    - name: Login to DockerHub
-      uses: docker/login-action@v3
-      with:
-        username: ${{ secrets.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Login to DockerHub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-    - name: Build and Push action
-      uses: docker/build-push-action@v6
-      with:
-        context: .
-        file: ./Dockerfile
-        push: true
-        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go:${{github.run_id}}
+      - name: Build and Push action
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: ./Dockerfile
+          push: true
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go:${{ github.run_id }}
 
   update-newtag-in-helm-chart:
+    if: ${{ github.event_name != 'push' }}
     runs-on: ubuntu-latest
-
     needs: push
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-      with:
-        token: ${{ secrets.TOKEN }}
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.TOKEN }}
 
-    - name: Update tag in Helm chart
-      run: |
-        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml
+      - name: Update tag in Helm chart
+        run: |
+          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/go-web-app-chart/values.yaml
 
-    - name: Commit and push changes
-      run: |
-        git config --global user.email "alok63579@gmail.com"
-        git config --global user.name "alokkodzz"
-        git fetch origin
-        git checkout ${{ github.head_ref || github.ref_name }}  # Ensure you're on the correct branch
-        git add helm/go-web-app-chart/values.yaml
-        git commit -m "Update tag in Helm chart [skip ci]" || echo "No changes to commit"  # Avoid errors if no changes
-        git push origin ${{ github.head_ref || github.ref_name }}
+      - name: Commit and push changes
+        run: |
+          git config --global user.email "alok63579@gmail.com"
+          git config --global user.name "alokkodzz"
+          git fetch origin
+          git checkout ${{ github.head_ref || github.ref_name }}
+          git add helm/go-web-app-chart/values.yaml
+          git commit -m "Update tag in Helm chart [skip ci]" || echo "No changes to commit"  # Avoid errors if no changes
+          git push origin ${{ github.head_ref || github.ref_name }}
